version: '3.4'

services:

  masstransit.demo.webapia:
    image: masstransit.demo.webapia
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/1_Sending_Message/WebApiA/Dockerfile
    ports:
      - "5010:443"
    volumes:
      - ./configs:/app/configs:ro

  masstransit.demo.webapib:
    image: masstransit.demo.webapib
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/1_Sending_Message/WebApiB/Dockerfile
    ports:
      - "5011:443"
    volumes:
      - ./configs:/app/configs:ro
  
  masstransit.demo.webapix:
    image: masstransit.demo.webapix
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/2_Publishing_Events/WebApiX/Dockerfile
    ports:
      - "5020:443"
    volumes:
      - ./configs:/app/configs:ro
  
  masstransit.demo.webapiy:
    image: masstransit.demo.webapiy
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/2_Publishing_Events/WebApiY/Dockerfile
    ports:
      - "5021:443"
    volumes:
      - ./configs:/app/configs:ro
  
  masstransit.demo.webapiz:
    image: masstransit.demo.webapiz
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/2_Publishing_Events/WebApiY/Dockerfile
    ports:
      - "5022:443"
    volumes:
      - ./configs:/app/configs:ro

  masstransit.demo.rabbitmq:
    image: rabbitmq:3.8.11-management-alpine
    container_name: masstransit.demo.rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
    volumes:
      - masstransit-demo-rabbitmq:/var/lib/rabbitmq/mnesia

  masstransit.demo.mongo:
    image: mongo
    container_name: masstransit.demo.mongo
    restart: unless-stopped
    ports:
      - "27017:27017"      

  masstransit.demo.mongoclient:
    image: mongoclient/mongoclient:4.0.0
    container_name: masstransit.demo.mongoclient
    restart: unless-stopped
    ports:
      - "5000:3000"
    volumes:
      - masstransit-demo-mongoclient:/data/db mongoclient/mongoclient

  masstransit.demo.seq:
    image: datalust/seq:latest
    container_name: masstransit.demo.seq
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

volumes:
  masstransit-demo-rabbitmq:
  masstransit-demo-mongoclient:
